# Generated by Django 5.2.7 on 2026-03-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('admin', 'Administrator'), ('employee', 'Employee'), ('secretary', 'Secretary')], max_length=100, null=True),
        ),
    ]
