# Generated by Django 5.2.7 on 2026-03-25 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_first_login',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Administrator'), ('employee', 'Employee'), ('secretary', 'Secretary')], max_length=100),
        ),
        migrations.DeleteModel(
            name='Timetable',
        ),
    ]
