# Generated by Django 5.2.7 on 2026-03-25 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_is_first_login_alter_customuser_user_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_first_login',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('admin', 'Administrator'), ('employee', 'Employee'), ('secretary', 'Secretary')], max_length=100, null=True),
        ),
    ]
