# Generated by Django 5.2.5 on 2025-09-19 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('in', 'scanned_at'), ('out', 'check_out_at')], default='in', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 9, 19, 19, 52, 27, 425932, tzinfo=datetime.timezone.utc)),
        ),
    ]
