# Generated by Django 5.2.5 on 2025-09-19 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendancerecord_status_alter_attendancerecord_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 9, 19, 19, 52, 35, 203195, tzinfo=datetime.timezone.utc)),
        ),
    ]
