# Generated by Django 5.2.5 on 2025-09-19 20:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_attendancerecord_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 9, 19, 20, 26, 59, 564633, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('scanned_at', 'scanned_at'), ('check_out_at', 'check_out_at')], max_length=20),
        ),
    ]
