# Generated by Django 5.2.7 on 2025-11-03 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_attendancerecord_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 11, 3, 11, 15, 30, 930045, tzinfo=datetime.timezone.utc)),
        ),
    ]
