# Generated by Django 5.2.7 on 2026-03-23 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_alter_attendancerecord_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 3, 23, 8, 14, 51, 818047, tzinfo=datetime.timezone.utc)),
        ),
    ]
