# Generated by Django 5.2.7 on 2026-03-25 03:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_alter_attendancerecord_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 3, 25, 3, 24, 0, 859625, tzinfo=datetime.timezone.utc)),
        ),
    ]
