# Generated by Django 5.2.1 on 2025-08-25 04:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_alter_attendancerecord_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 8, 25, 4, 34, 8, 171059, tzinfo=datetime.timezone.utc)),
        ),
    ]
