# Generated by Django 5.2.5 on 2025-08-26 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_alter_attendancerecord_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 8, 26, 20, 10, 37, 459898, tzinfo=datetime.timezone.utc)),
        ),
    ]
