# Generated by Django 5.2.7 on 2026-03-25 04:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_alter_attendancerecord_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 3, 25, 4, 32, 25, 74241, tzinfo=datetime.timezone.utc)),
        ),
    ]
