# Generated by Django 5.2.5 on 2025-08-28 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_alter_attendancerecord_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 8, 28, 18, 48, 22, 76591, tzinfo=datetime.timezone.utc)),
        ),
    ]
