# Generated by Django 5.2.7 on 2026-03-30 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_alter_attendancerecord_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 3, 30, 9, 16, 33, 197429, tzinfo=datetime.timezone.utc)),
        ),
    ]
